import Auth from "@/auth/Auth";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import ToastWrapper from "@/components/Toast/ToastWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Auth>
      <html lang="en">
        <body className={inter.className}>
          <ToastWrapper>
            <main className="min-h-screen flex flex-col">
              <Navbar />
              <div className="py-20 px-8">{children}</div>
            </main>
          </ToastWrapper>
        </body>
      </html>
    </Auth>
  );
}
